# Run Ubuntu
FROM ubuntu:latest

# Update and Upgrade Packages
RUN apt-get update
RUN apt-get upgrade -y

# Install nano, python, pip
RUN apt-get install nano -y
RUN apt-get install python-is-python3 -y
RUN apt-get install python3-pip -y
